### ISSUE TITLE
reconnect_interval not used for reconnect, Stud::try log not in Logstash log file

### ISSUE THREAD

**Issue by breml** [logstash-plugins/logstash-output-tcp#12]
For reconnects `Stud::try` is used (https://github.com/logstash-plugins/logstash-output-tcp/blob/master/lib/logstash/outputs/tcp.rb#L123), which has two side effects:
1. `Stud::try` does not respect the `reconnect_interval` configured for the plugin but its own intervals, defined in https://github.com/jordansissel/ruby-stud/blob/master/lib/stud/try.rb#L26
2. `Stud::try` does not log to the Logstash log file but to stdout, which makes problem finding very difficult, if logstash is executed as a service.

**Comment by PaddyFOpenet** [comment]
Just wondering if there was any consideration given to this; `Stud:try` preventing `reconnect_interval `from having an affect seems like a bug to me?
